name: Release

on:
  push:
    branches: [main]

jobs:
  release:
<<<<<<< HEAD
    uses: ${{ github.repository_owner }}/github-workflows/.github/workflows/release.yml@main
=======
    uses: adelynnmckay/github-workflows/.github/workflows/release.your-username
>>>>>>> adelynnmckay
    with:
      repo_owner: ${{ github.repository_owner }}
      repo_name: ${{ github.event.repository.name }}
    secrets: inherit
