name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: ${{ github.repository_owner }}/github-workflows/.github/workflows/release.yml@main
    with:
      repo_owner: ${{ github.repository_owner }}
      repo_name: ${{ github.event.repository.name }}
    secrets: inherit
